name: test
on: [push]

env:
  TAG_PREFIX: artifactory.hashicorp.engineering/actions-docker-build/test

jobs:

  bats-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install BATS
        env:
          BATS_VERSION: 1.5.0
          BATS_REPO: https://github.com/bats-core/bats-core
          BATS_PATH: /usr/local/bats
        run: |
          sudo git clone --depth 1 --branch v$BATS_VERSION $BATS_REPO $BATS_PATH
          echo $BATS_PATH/bin >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: Run BATS tests
        run: make test

  # The action we're testing expects to download an artifact,
  # so here we upload it in preperation.
  action-test-prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Zip Test Bin
        run: |
          zip ./testdata/test_bin.zip ./testdata/test_bin
      - name: Upload a test artifact.
        uses: actions/upload-artifact@v2
        with:
          path: testdata/test_bin.zip
          name: test_bin.zip

  action-test-dockerfile-in-root:
    runs-on: ubuntu-latest
    env:
      OVERRIDE_TARBALL_NAME: action-test-dockerfile-in-root.docker.tar
    needs:
      - action-test-prep
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      # Test setup.
      - name: Move Dockerfile to Repo Root
        run: |
          mv testdata/Dockerfile ./
          ls -lah
      - name: Invoke Action
        uses: ./ # This is the action we're testing.
        with:
          version: 1.0.0
          target: default
          arch: amd64
          tags: |
            ${{env.TAG_PREFIX}}/action-test-dockerfile-in-root:tag1
            ${{env.TAG_PREFIX}}/action-test-dockerfile-in-root:tag2
          zip_artifact_name: test_bin.zip
          bin_name: test_bin
          # No overrides to Dockerfile path.
      - name: Assert Tarball Created And Contains Correct Tags
        run: |
          source scripts/assertions.bash
          REPO="${{env.TAG_PREFIX}}/action-test-dockerfile-in-root"
          assert_tarball_contains_tags "$OVERRIDE_TARBALL_NAME" "$REPO:tag1" "$REPO:tag2"

  action-test-setting-dockerfile:
    runs-on: ubuntu-latest
    env:
      OVERRIDE_TARBALL_NAME: action-test-setting-dockerfile.docker.tar
    needs:
      - action-test-prep
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Invoke Action
        uses: ./ # This is the action we're testing.
        with:
          version: 1.0.0
          target: default
          arch: amd64
          tags: |
            ${{env.TAG_PREFIX}}/action-test-setting-dockerfile:tag1
            ${{env.TAG_PREFIX}}/action-test-setting-dockerfile:tag2
          zip_artifact_name: test_bin.zip
          bin_name: test_bin
          # Test setting just dockerfile.
          dockerfile: testdata/Dockerfile
      - name: Assert Tarball Created And Contains Correct Tags
        run: |
          source scripts/assertions.bash
          REPO="${{env.TAG_PREFIX}}/action-test-setting-dockerfile"
          assert_tarball_contains_tags "$OVERRIDE_TARBALL_NAME" "$REPO:tag1" "$REPO:tag2"

  action-test-setting-workdir:
    runs-on: ubuntu-latest
    env:
      OVERRIDE_TARBALL_NAME: action-test-setting-workdir.docker.tar
    needs:
      - action-test-prep
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Invoke Action
        uses: ./ # This is the action we're testing.
        with:
          version: 1.0.0
          target: default
          arch: amd64
          tags: |
            ${{env.TAG_PREFIX}}/action-test-setting-workdir:tag1
            ${{env.TAG_PREFIX}}/action-test-setting-workdir:tag2
          zip_artifact_name: test_bin.zip
          bin_name: test_bin
          # Test setting just workdir.
          workdir: testdata
      - name: Assert Tarball Created And Contains Correct Tags
        run: |
          source scripts/assertions.bash
          REPO="${{env.TAG_PREFIX}}/action-test-setting-workdir"
          assert_tarball_contains_tags "$OVERRIDE_TARBALL_NAME" "$REPO:tag1" "$REPO:tag2"
